"""add pptx table

Revision ID: 3ddbe266355d
Revises: 593747afa3d6
Create Date: 2026-08-19 15:31:42.899988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddbe266355d'
down_revision: Union[str, Sequence[str], None] = '593747afa3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import sqlalchemy as sa
    from alembic import op
    bind = op.get_bind()
    # Check if pptx table already exists (e.g. created by main.py auto-migration)
    if bind.dialect.name == 'sqlite':
        result = bind.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name='pptx'"))
    else:
        result = bind.execute(sa.text("SHOW TABLES LIKE 'pptx'"))
    if not result.fetchone():
        op.create_table('pptx',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('lesson_id', sa.Integer(), nullable=False),
        sa.Column('layouts_json', sa.Text(), nullable=False),
        sa.Column('selected_layout', sa.String(length=20), nullable=False),
        sa.Column('brand_colors', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('lesson_id')
        )
        op.create_index(op.f('ix_pptx_lesson_id'), 'pptx', ['lesson_id'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pptx_lesson_id'), table_name='pptx')
    op.drop_table('pptx')
    # ### end Alembic commands ###